version: '3.8'

services:
  web:
    image: ranbir18/backend:latest
    ports:
      - "5000:5000"
    deploy:
      replicas: 3
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure

  db:
    image: postgres:13
    environment:
      POSTGRES_USER: ranbir
      POSTGRES_PASSWORD: Saini@1994
      POSTGRES_DB: myappdb
    volumes:
      - db-data:/var/lib/postgresql/data
    deploy:
      resources:
        limits:
          cpus: '0.5'
          memory: 512M
      restart_policy:
        condition: on-failure

volumes:
  db-data:
