apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-my-app
  namespace: {{ .Release.Namespace }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: flask-backend
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
        - containerPort: {{ .Values.service.port }}
        env:
        - name: PORT
          value: "{{ .Values.service.port }}"
      - name: nginx-frontend
        image: nginx:latest
        ports:
        - containerPort: 80
        volumeMounts:
        - name: frontend-volume
          mountPath: /usr/share/nginx/html
      volumes:
      - name: frontend-volume
        configMap:
          name: {{ .Release.Name }}-frontend-config
